# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title FastProxSL1
#' @description
#' A function using RcppArmadillo that computes the proximal operator for SLOPE using Algorithm 3 (FastProxSL1) from Bogdan et al 2015 (SLOPE: adaptive variable selection via convex optimization).
#' @name FastProxSL1
#' @param beta input vector
#' @param lambda vector of lambdas, sorted in decreasing order
#' @examples
#' p = 1e7
NULL

#' FastProxSL1(y, lambda)
#' 
#' @export
#' 
#' 
NULL

FastProxSL1 <- function(beta, lambda) {
    .Call(`_ADMMSLOPE_FastProxSL1`, beta, lambda)
}

rcpparma_hello_world <- function() {
    .Call(`_ADMMSLOPE_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_ADMMSLOPE_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_ADMMSLOPE_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_ADMMSLOPE_rcpparma_bothproducts`, x)
}

#' @title ADMM
#' @description
#' ADMM to solve SLOPE-penalized ordinary least squares regression.
#' @name ADMM
#' @param X matrix of independent  variables
#' @param Y vector of dependent variables
#' @param max_iter maximum number of iterations of the ADMM loop
#' @param rho augmented Lagrangian parameter
#' @examples
#' library(SLOPE)
#' fit <- ADMM(as.matrix(bodyfat$x), bodyfat$y, 1e4, 1)
#' 
#' @export
#' 
#' 
NULL

ADMM <- function(X, Y, lambda, max_iter, rho) {
    .Call(`_ADMMSLOPE_ADMM`, X, Y, lambda, max_iter, rho)
}

